#!/usr/bin/env python3
#9x9 Sudoku Solver in Python3
#07SEP2018
#Author: Mohammed S. Haque <ubdussamad@gmail.com>

#Though default version for this code is 3.x but it's is written in a way that may support 2.x as well.
import sys,time
class loader: #For loading the target sudoku puzzle file
    path_to_sudoku = sys.argv[1] if len(sys.argv) > 1 else "s1"
    sudoku_file_object = None if not(path_to_sudoku) else open(path_to_sudoku,'r')
    sudoku = sudoku_file_object.read() if sudoku_file_object else -1
    sudoku = [i for i in sudoku.split('\n') if i]
    sudoku = [list(i) for i in sudoku] 

class parser(object): #Loads and defines all the methods which can be 
    def __init__(self,sudoku): # used to manipulate or read a sudoku.
        self.sudoku = sudoku
        self.current_index = -1
        self.empty_indices = []
        self.dim = len(sudoku)
        self.parent_list = [ str(i) for i in range(1,self.dim+1)]
        self.prams = []
        self.find_empty_indices()
        print("Hello, Your sudoku grid is:%dx%d and the complexity is: %.2f Percent "%(self.dim,self.dim, (len(self.empty_indices)/(self.dim**2))*100 ) )

    def get_grid_elements(self,pos):
        #Returns all the elements inside the grid scope of the given position
        #(Only works for 6x6 and 9x9 sudokus)
        #Divides the columns into triplets or duplets and then finds all the numbers in the grid
        quad_members = []
        def get_range(coord,a,b,parity=0):
            itr = b if parity else a
            for i in itr:
                if coord in itr[i]:
                    return(i)
            return(-1)

        if self.dim==6:#Grid Ranges for 6x6 arrays
            ri = {i:range(j,k+1) for i,j,k in zip(range(1,4),range(0,6,2),range(1,6,2))}
            rj = {i:range(j,k+1) for i,j,k in zip(range(1,3),range(0,5,3),range(2,6,3))}
        
        elif self.dim==9:#Grid ranges for 9x9 arrays.
            ri = rj = {i:range(j,k+1) for i,j,k in zip(range(1,4),range(0,7,3),range(2,9,3))}

        row_triplet,column_triplet = get_range(pos[0],ri,rj) , get_range(pos[1],ri,rj,1)
        
        for i in ri[row_triplet]:
            for j in rj[column_triplet]:
                if int(self.sudoku[i][j]):
                	quad_members.append(self.sudoku[i][j])
        return(quad_members)
        
    def find_empty_indices(self):
        for i,j in enumerate(self.sudoku):
            for k,l in enumerate(j):
                if l == "0":self.empty_indices.append([i,k])

    def set_index(self,pos):
        index = self.empty_indices.index(pos)
        self.current_index = index

    def next(self): # Calling next for the first time starts the counter and returns first position.
        self.current_index += 1
        return self.empty_indices[self.current_index]

    def get_options(self,pos):
        return [ i for i in self.parent_list if i not in set(self.get_neighbours(pos)+self.get_grid_elements(pos))]

    def previous(self):
        self.current_index -= 1
        return self.empty_indices[self.current_index]
    
    def current(self):
        return( self.empty_indices[self.current_index])

    def get_neighbours(self,pos):
        i,j = pos
        neighbours_list = [ self.sudoku[i][k] for k in range(0,self.dim) if int(self.sudoku[i][k])] #Keeping i Constant
        neighbours_list += [ self.sudoku[k][j] for k in range(0,self.dim) if int(self.sudoku[k][j])]
        return neighbours_list

    def p(self):
        print()
        for i in self.sudoku:
            print("|",end="")
            for j in i:
                print(j,end="|")
            print()
        print()

    def challenge(self):
        return(len(self.empty_indices))

counter=0
#Solving Logic
def solve(z,v=0):
    global counter
    counter+=1
    try:
        pos = z.next()
    except:
        return(0)

    op = z.get_options(pos) #Get all the available options

    if not(len(op)):
        print("Rolling Back!\n" if v else "",end="")
        z.set_index(z.previous())
        return(-1)

    while 1:
        if v:print("Current Position is:",pos,"and current options are:",op)
        
        if not(len(op)):
            print("Rolling Back!\n" if v else "",end="")
            z.sudoku[pos[0]][pos[1]] =  0
            z.set_index(z.previous())
            return(-1)
        ch = op.pop()
        if v:print("We chose:",ch)
        
        z.sudoku[pos[0]][pos[1]] =  ch#MO
        
        call = solve(z,v)

        if call == 0:
            return(0)
        elif call == -1:
            continue
        else:
            print("An Unexpected Error occurred!")

if __name__ == "__main__":
	z = parser(loader.sudoku) 
	initial  = time.time()
	solve(z,sys.argv[2] if len(sys.argv)>2 else 0)
	print("Time taken to solve:%.2fs in %d steps."%(time.time()-initial , counter))
	z.p()
